apiVersion: skaffold/v1
kind: Config
deploy:
  helm:
    releases:
    - name: ired-mglasiatwo
      chartPath: ./ired
      namespace: ired
      #wait: true
      # valuesFiles:
      # - ./values.yaml
      #recreatePods will pass --recreate-pods to helm upgrade
      recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue             